package Constants;

public enum SystemCommandType {
    HEALTH, MOVES_LEFT, FIRE_POWER, TEAM, MEMBER, CONSOLE, RANDOM, SHOOT, MOVE, SCAN, IDENTIFY, MAIL_SEND, MAIL_CHECK, MAIL_RECIEVE, HEX, VAR_CHECK, VAR_ASSIGN, AND, OR, INVERT, LESS, LESS_EQUAL, EQUAL, NOT_EQUAL, GREATER_EQUAL, GREATER, ADD, SUBTRACT, MULTIPLY, DIVIDE, DROP, DUPLICATE, SWAP, ROTATE, NOT_FORTH_WORD
}
